### ISSUE TITLE
Getting the exception

### ISSUE THREAD

**Issue by ujwalthote** [mmuszkow/ScreenMirroring#2]
Cannot start server
    java.io.IOException: Cannot run program "su": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
        at java.lang.Runtime.exec(Runtime.java:691)
        at java.lang.Runtime.exec(Runtime.java:524)
        at java.lang.Runtime.exec(Runtime.java:421)
        at pl.muh.screenmirroring.GrabbingService.onCreate(GrabbingService.java:31)

**Comment by mmuszkow** [comment]
https://github.com/mmuszkow/ScreenMirroring/issues/1
